---

- name: nginx installation
  hosts: all
  become: true
  gather_facts: true
  tasks:

  - name: update and install nginx package
    tags: nginx
    package:
      name: "{{ nginx_package }}"
      state: latest
      update_cache: yes

