---

- name: nginx installation
  hosts: all
  become: true
  gather_facts: true
  tasks:

  - name: update and install nginx package
    tags: nginx
    package:
      name: "{{ nginx_package }}"
      state: latest
      update_cache: yes

  - name: copy default html file to server
    tags: copy, nginx
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: '0644'
